name: flutter_assignment
description: "Mobile Developer Assignment – Intern"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # Basic Flutter dependencies
  cupertino_icons: ^1.0.8

  # State management (MVVM)
  provider: ^6.1.2

  # SQLite for local database operations
  sqflite: ^2.4.1

  # To locate the database file path
  path_provider: ^2.1.5

  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Linting package
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
